language: node_js
node_js:
  - "4.4"
  - "4.0"
  - "0.12"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start